DEFAULT linux

LABEL linux
    KERNEL /boot/Image.gz
    FDT /boot/msm8953-motorola-sanders.dtb
    INITRD /boot/initramfs.cpio.gz
    APPEND console=tty0 console=ttyGS0 console=ttyMSM0,115200n8 earlycon ignore_loglevel printk.time=1 printk.devkmsg=on panic=30 fbcon=font:TER16x32 consoleblank=60
